version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  ContactUs:
    executor: node/default
    steps:
      - checkout
      - browser-tools/install-browser-tools

      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            npm install
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/ContactUs.js

  SearchDress:
    executor: node/default
    steps:
      - checkout
      - browser-tools/install-browser-tools

      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            npm install
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/SearchDress.js

workflows:
  test_my_app:
    jobs:
      - ContactUs
      - SearchDress
