version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/node:lts-browsers

jobs:
  RunServerAPI:
    executor: my-executor
    working_directory: ~/QA-Task/API/MockUser

    steps:
      - checkout:
          path: ~/QA-Task
      - run:
          name: "Install Mock-User-Auth and Supertest"
          command: |
            npm install mock-user-auth
            npm install supertest --save-dev
            npm install --save-dev mocha
            npm install --save-dev mochawesome
            npm install nodemon --save-dev
      - run:
          name: "Start Mock-User-Auth server"
          background: true
          command: |
            sudo chmod +x node_modules/mock-user-auth/bin/www.js
            npm run dev
            echo "export SERVER_IP=$(ifconfig eth0 | grep 'inet ' | awk '{print $2}') >> $BASH_ENV"
            echo "export SERVER_PORT=3000" >> $BASH_ENV

  ExecuteAPI:
    executor: my-executor
    working_directory: ~/QA-Task/API/MockUser

    steps:
      - attach_workspace:
          at: ~/QA-Task
      - run:
          name: "Execute API tests"
          command: |
            source $BASH_ENV
            echo "Connecting to server at $SERVER_IP:$SERVER_PORT"
            sleep 30
            npx mocha api.test.js --port $SERVER_PORT
          when: always
      - store_artifacts:
          path: API/MockUser/mochawesome-report/

workflows:
  version: 2
  build-and-test:
    jobs:
      - RunServerAPI:
          name: Run Server API
      - ExecuteAPI:
          name: Execute API
          requires:
            - RunServerAPI
