version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.0 # Choose the appropriate Docker image for your project
    steps:
      - checkout
      - run:
          name: Run UI Tests
          command: |
            npm init nightwatch
            npx nightwatch test/MyStore/ContactUs.js