version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  ContactUs:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task

      - browser-tools/install-chrome
      - node/install-packages   

      - run:
          name: Run Contact Us
          command: 
            npx nightwatch test/MyStore/ContactUs.js

  SearchDress:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task      
      - browser-tools/install-chrome
      - node/install-packages 

      - run:
          name: Run Search Dress
          command: 
            npx nightwatch test/MyStore/SearchDress.js

workflows:
  test:
    jobs:
      - ContactUs
      - SearchDress