version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  ContactUs:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npx nightwatch test/MyStore/ContactUs.js
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test:
    jobs:
      - ContactUs


  