version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.1
  
executors:
  my-executor:
    docker:
      - image: cimg/node:lts-browsers


jobs:
  TestAPIs:
    executor: my-executor
    working_directory: ~/QA-Task/API/MockUser

    steps:
      - checkout:
          path: ~/QA-Task
      
      - run:
          name: "Install Mock-User-Auth and Supertest"
          command: |
             npm install mock-user-auth
             npm install supertest --save-dev
             npm install --save-dev mocha
             npm install --save-dev mochawesome
             npm install nodemon --save-dev

      - run:
          name: Start Mock-User-Auth server
          background: true
          command: |
            npm run dev

      - run:
          name: Execute API tests
          command: |
            sleep 10
            sudo chmod +x node_modules/.bin/mocha
            npx mocha api.test.js --endpoint http://localhost:3000 


          when: on_success

  ContactUs:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task

      - browser-tools/install-chrome
      - node/install-packages   

      - run:
          name: Run Contact Us
          command: 
            npx nightwatch test/MyStore/ContactUs.js

      - store_artifacts:
          path: tests_output/

  SearchDress:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task      
      - browser-tools/install-chrome
      - node/install-packages 

      - run:
          name: Run Search Dress
          command: 
            npx nightwatch test/MyStore/SearchDress.js
      - store_artifacts:
          path: tests_output/

workflows:
  version: 2
  build-and-test:
    jobs:
      - TestAPIs
      - ContactUs
      - SearchDress
