version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.1

executors:
  my-executor:
    docker:
      - image: cimg/node:lts-browsers

jobs:
  RunServerAPI:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "Install Mock-User-Auth and Supertest"
          command: |
            npm install mock-user-auth
            npm install supertest --save-dev
            npm install --save-dev mocha
            npm install --save-dev mochawesome
      - run:
          name: "Start Mock-User-Auth server"
          background: true
          command: |
            npm run dev

  ExecuteAPI:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/QA-Task/

      - run:
          name: "Execute API tests"
          command: |
            cd API/MockUser
            chmod +x node_modules/.bin/mocha
            sleep 20
            npx mocha api.test.js  
      - store_artifacts:
          path: API/MockUser/mochawesome-report/

  ContactUs:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task

      - browser-tools/install-chrome
      - node/install-packages   

      - run:
          name: Run Contact Us
          command: 
            npx nightwatch test/MyStore/ContactUs.js

      - store_artifacts:
          path: tests_output/

  SearchDress:
    docker:
      -  image: cimg/node:lts-browsers
    working_directory: ~/QA-Task/UI/NightWatch
    steps:
      - checkout:
          path: ~/QA-Task      
      - browser-tools/install-chrome
      - node/install-packages 

      - run:
          name: Run Search Dress
          command: 
            npx nightwatch test/MyStore/SearchDress.js
      - store_artifacts:
          path: tests_output/

workflows:
  test:
    jobs:
      - RunServerAPI
      - ExecuteAPI:
          requires:
            - RunServerAPI
      - SearchDress
      - ContactUs

