version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Nightwatch Dependencies
          command: |
            cd UI/NightWatch
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/ContactUs.js


workflows:
  test_my_app:
    jobs:
      - test
