version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  ContactUs:
    executor: node/default
    steps:
      - checkout
      
      - run:
          command: |
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - run:
          name: Install Nightwatch Dependencies
          command: |
            cd UI/NightWatch
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/ContactUs.js

  SearchDress:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Nightwatch Dependencies
          command: |
            cd UI/NightWatch
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/SearchDress.js

workflows:
  test_my_app:
    jobs:
      - ContactUs
      - SearchDress
