version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  ContactUs:
    docker:
      -  image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages   

      - run:
          name: Run UI Tests
          command: 
            npx nightwatch test/MyStore/ContactUs.js

  SearchDress:
    docker:
      -  image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages   

      - run:
          name: Run UI Tests
          command: |
            cd UI/NightWatch
            npm install
            chmod -R a+x node_modules
            npx nightwatch test/MyStore/SearchDress.js

workflows:
  test_my_app:
    jobs:
      - ContactUs
      - SearchDress
