version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3 # Choose the appropriate Docker image for your project
    steps:
      - checkout
      - run:
          name: Run UI Tests
          command: npx nightwatch test/MyStore/ContactUs.j 



  