version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run UI Tests
          command: |
            npm init nightwatch
            nightwatch --config ./UI/NightWatch/test/nightwatch.conf.js --env default --test test/MyStore/ContactUs.js

workflows:
  test_my_app:
    jobs:
    - test